data = {
  "3D View: POPOTI Align Helper": "3D 视图: POPOTI对齐助手",
  "POPOTI Align Helper": "POPOTI对齐助手",
  "World Original": "世界原点",
  "More friendly alignment based on observation perspective": "更友好的基于观察视角的对齐",
  "Tool Panel": "工具面板",
  "Axis to be aligned": "需要对齐的轴",
  "Select the axis to be aligned, multiple choices are allowed": "选择需要进行对齐的轴,可多选",
  "Align X Axis": "对齐X轴",
  "Align Y Axis": "对齐Y轴",
  "Align Z Axis": "对齐Z轴",
  "Min Point": "最小点",
  "Max Point": "最大点",
  "Center Align": "中心对齐",
  "Align to Min Point": "对齐到最小点",
  "Align to Max Point": "对齐到最大点",
  "Distribution": "分布",
  "Distribution Align": "分布对齐",
  "General alignment, you can set the alignment of each axis(maximum, center, minimum)": "常规对齐,可以设置每个轴的对齐方式(最大,居中,最小)",
  "Align to Cursor(Scale reset 1)": "对齐到游标(缩放将重置为1)",
  "Align to Active Object": "对齐到活动物体",
  "Aligning to the world origin is the same as resetting": "对齐到世界原点,和重置功能相同",
  "Sort distribution by X axis": "按X轴排序分布",
  "Sort distribution by Y axis": "按Y轴排序分布",
  "Sort distribution by Z axis": "按Z轴排序分布",
  "Align and sort the selected objects according to the selection axis to obtain the correct movement position": "按选择轴对所选物体进行对齐并排序,以获取正确的移动位置",
  "Distribution sort axis": "分布排序轴",
  "Lowest Object": "最低物体",
  "All Object": "所有物体",
  "Sort Axis": "排序轴",
  "Ground": "地面",
  "Align Ground": "对齐地面",
  "Adjustment": "调整",
  "Distribution interval value": "分布间隔距离",
  "Active": "活动项",
  "Not Selected Active Object": "未选择活动物体",
  "Fixed the nearest and farthest objects": "固定最远和最近的物体,按间距自动排列中间的物体",
  "Adjust the distance between each object(Fixed active object)": "调整每个对象之间的距离(固定活动对象位置)",
  "Show Button Text": "显示按钮文字",
  "Align To Ground Object": "对齐到地面物体",
  "To Object": "到物体",
  "Left Up": "左上",
  "Up": "上",
  "Right Up": "右上",
  "Center": "中心",
  "Object Align by View": "按视图对齐物体",
  "Down Mode": "下降模式",
  "Ground Plane Mode": "地面平面模式",
  "Fall": "坠落",
  "Ray Casting Rotation": "光线投射旋转",
  "Align Objects\nCtrl    Align Rotation\nShift  Align Zoom\nAlt     Align Position\nCombined presses": "对齐物体\nCtrl    对齐旋转\nShift   对齐缩放\nAlt     对齐位置\n可组合按",
  "Please select at least one object": "请至少选择一个物体",

  "Ctrl: only location": "Ctrl: 仅位置",
  "Shift: only rotation": "Shift: 仅旋转",
  "Align Mesh": "对齐网格",
  "Horizontal": "水平",
  "Vertical": "垂直",
  "Alignment to the origin (world axis)": "对齐到原点(世界坐标轴)",
  "Axis:": "轴:",
  "Align to Cursor": "对齐到游标",
  "Alignment according to the position of the bounding box of the selected mesh, each axis can be set individually (minimum position, center position, maximum position)":
    "根据所选网格的边界框位置对齐,每个轴可以单独设置对齐方法(最小位置,居中位置,最大位置)",
  "Alignment according to the position of the bounding box of the selected mesh": "根据所选网格的边界框位置对齐",
  "each axis can be set individually (minimum position, center position, maximum position)": "每个轴可以单独设置对齐方法(最小位置,居中位置,最大位置)",
  "Aligns to the active item %s": "对齐到活动项 %s",
  "Aligns to the active item": "对齐到活动项",
  "or to the center of the selected grid if the active item is not selected": "如果未选择活动项目,则移至所选网格的中心位置",
  "Align selected objects to world origin": "将所选物体对齐到世界原点",
  "Drawing the selected surface will switch to the drawing mode and only the selected surface will be displayed for drawing": "绘制选中的面,将会切换到绘制模式,并只显示选中的面进行绘制",
  "Setting the edge crease of the selected edge": "设置所选边的边线折痕",
  "Setting the edge bevel weight of the selected edge": "设置所选边的倒角权重",
  "Including through": "包含",
  "Crease Edge": "折痕",
  "Edge Weight": "边权重",
  "Seam Edge": "缝合边",
  "Sharp Edge": "锐边",
  "Freestyle Edge": "Freestyle边",
  "Clear all edge property": "清理所有边属性",
  "Transform Pie": "变换饼菜单",
  "Snap Pie": "捕捉饼菜单",
  "Not Find": "未找到",
  "Down": "下",
  "Left": "左",
  "Right": "右",
  "Left Down": "左下",
  "Right Down": "右下",
  "Align UV": "对齐UV"
}
